# Generated by Django 4.2.30 on 2026-10-04 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SequenceMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(help_text='0-based order of the campaign inside the sequence.')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='inventory.campaign')),
            ],
            options={
                'ordering': ['sequence', 'position'],
            },
        ),
        migrations.AddField(
            model_name='identityconflict',
            name='hint',
            field=models.CharField(choices=[('same_number_position_mismatch', 'Same number, contradictory position'), ('same_label_extra_row', 'Extra row reusing a label'), ('possible_renumber', 'New number near an old position'), ('gap_reappearance', 'Reappears after a missing occasion (gap)')], default='same_number_position_mismatch', help_text='Machine-readable reason this item is held.', max_length=32),
        ),
        migrations.AlterField(
            model_name='identityconflict',
            name='distance_m',
            field=models.FloatField(blank=True, help_text='Distance between the two reported positions [m]; null when one side has no position in this interval.', null=True),
        ),
        migrations.AlterField(
            model_name='identityconflict',
            name='t1_measurement',
            field=models.ForeignKey(blank=True, help_text='Null when nothing for this tree exists at t1 (gap).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conflicts_as_t1', to='inventory.treemeasurement'),
        ),
        migrations.CreateModel(
            name='SurveySequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('status', models.CharField(choices=[('active', 'Active — new remeasurements may be appended'), ('closed', 'Closed')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaigns', models.ManyToManyField(related_name='sequences', through='inventory.SequenceMembership', to='inventory.campaign')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='SurveyInterval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal', models.PositiveIntegerField(help_text='0-based link index: 0 = first pair of occasions.')),
                ('status', models.CharField(choices=[('pending', 'Pending — links not yet built'), ('built', 'Built — coverage/identity materialised')], default='pending', max_length=10)),
                ('coverage_snapshot', models.JSONField(blank=True, help_text='Coverage state at both ends + fingerprint {status, fingerprint, n_t1, n_t2, per_plot, built_at}.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('built_at', models.DateTimeField(blank=True, null=True)),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='intervals', to='inventory.surveysequence')),
                ('t1_campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='intervals_as_t1', to='inventory.campaign')),
                ('t2_campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='intervals_as_t2', to='inventory.campaign')),
            ],
            options={
                'ordering': ['sequence', 'ordinal'],
                'unique_together': {('sequence', 'ordinal'), ('sequence', 't1_campaign', 't2_campaign')},
            },
        ),
        migrations.AddField(
            model_name='sequencemembership',
            name='sequence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='inventory.surveysequence'),
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_batch_id', models.CharField(max_length=120)),
                ('payload_fingerprint', models.CharField(max_length=64)),
                ('n_rows', models.PositiveIntegerField(default=0)),
                ('result_summary', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_batches', to='inventory.campaign')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('campaign', 'client_batch_id')},
            },
        ),
        migrations.AddField(
            model_name='estimateversion',
            name='interval',
            field=models.ForeignKey(blank=True, help_text='Chain link this edition belongs to. Legacy two-campaign editions leave this NULL and are never back-filled.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estimate_versions', to='inventory.surveyinterval'),
        ),
        migrations.AddField(
            model_name='measurementimportrow',
            name='batch',
            field=models.ForeignKey(blank=True, help_text='Idempotency envelope; retransmissions reuse the batch.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rows', to='inventory.importbatch'),
        ),
        migrations.AlterUniqueTogether(
            name='sequencemembership',
            unique_together={('sequence', 'campaign'), ('sequence', 'position')},
        ),
        migrations.CreateModel(
            name='IntervalLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t1_field_number', models.CharField(blank=True, max_length=16)),
                ('t2_field_number', models.CharField(blank=True, max_length=16)),
                ('kind', models.CharField(choices=[('survivor_same_number', 'Survivor — same tag'), ('survivor_renumber', 'Survivor — verified renumber'), ('survivor_zero_growth', 'Survivor — verified zero growth'), ('alive_not_measured', 'Alive at t2 but not measured'), ('mortality', 'Mortality'), ('ingrowth', 'Ingrowth'), ('below_recruitment', 'Below recruitment — recorded, excluded'), ('not_located_t2', 'Not located at t2'), ('removal_unobserved', 'Present t1 only — removal unobserved'), ('dead_at_t1', 'Already dead at t1 — no component this interval'), ('ingrowth_distinct_verified', 'Distinct recruit verified'), ('pending_same_number_mismatch', 'PENDING: same number, position mismatch'), ('possible_renumber', 'PENDING: possible unrecorded renumber'), ('gap_reappearance', 'PENDING: reappears after a gap (verify chain)'), ('gap_reappearance_verified', 'Gap reappearance human-verified (kept excluded)')], max_length=32)),
                ('determination', models.CharField(choices=[('data', 'Determined by tracked tree row'), ('human', 'Determined by human verification'), ('pending', 'Undetermined — held for verification')], default='pending', max_length=10)),
                ('excluded_from_components', models.BooleanField(default=False)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conflict', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interval_links', to='inventory.identityconflict')),
                ('interval', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='links', to='inventory.surveyinterval')),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.plot')),
                ('t1_measurement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='interval_links_as_t1', to='inventory.treemeasurement')),
                ('t1_tree', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='interval_links_as_t1', to='inventory.tree')),
                ('t2_measurement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='interval_links_as_t2', to='inventory.treemeasurement')),
                ('t2_tree', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='interval_links_as_t2', to='inventory.tree')),
            ],
            options={
                'ordering': ['interval', 'plot__code', 't2_field_number', 't1_field_number'],
                'indexes': [models.Index(fields=['interval', 'kind'], name='inventory_i_interva_31ee5f_idx'), models.Index(fields=['t2_tree'], name='inventory_i_t2_tree_d841d2_idx'), models.Index(fields=['t1_tree'], name='inventory_i_t1_tree_ac76ab_idx')],
            },
        ),
    ]
