# Generated by Django 4.2.30 on 2026-10-04 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SequenceCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequence_memberships', to='inventory.campaign')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='SurveySequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaigns', models.ManyToManyField(related_name='sequences', through='inventory.SequenceCampaign', to='inventory.campaign')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SurveyInterval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(help_text='Chain order of this interval at creation.')),
                ('coverage', models.CharField(choices=[('pending', 'Pending — far-end campaign has no data yet'), ('partial', 'Partial — some plots lack measurements'), ('covered', 'Covered — every plot measured at both ends')], default='pending', max_length=10)),
                ('is_adjacent', models.BooleanField(default=True, help_text='False when a later campaign insertion made this pair non-adjacent; kept for traceability, never rewritten.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervals', to='inventory.surveysequence')),
                ('t1_campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='intervals_as_t1', to='inventory.campaign')),
                ('t2_campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='intervals_as_t2', to='inventory.campaign')),
            ],
            options={
                'ordering': ['sequence', 'position'],
                'unique_together': {('sequence', 't1_campaign', 't2_campaign')},
            },
        ),
        migrations.AddField(
            model_name='sequencecampaign',
            name='sequence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='inventory.surveysequence'),
        ),
        migrations.AddField(
            model_name='estimateversion',
            name='interval',
            field=models.ForeignKey(blank=True, help_text='Adjacent survey interval this edition belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimate_versions', to='inventory.surveyinterval'),
        ),
        migrations.AlterUniqueTogether(
            name='sequencecampaign',
            unique_together={('sequence', 'position'), ('sequence', 'campaign')},
        ),
        migrations.CreateModel(
            name='IntervalIdentityLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('survivor', 'Survivor (measured both ends)'), ('survivor_renumber', 'Survivor via verified renumber'), ('survivor_unmeasured', 'Survivor with missing measurement'), ('mortality', 'Mortality'), ('not_located', 'Not located'), ('ingrowth', 'Ingrowth (reached threshold this interval)'), ('below_recruitment', 'Below recruitment threshold'), ('gap_reappearance', 'PENDING — reappeared after a missing occasion'), ('resurrected', 'PENDING — recorded dead, later alive'), ('identity_conflict', 'PENDING — unverified identity this interval')], max_length=24)),
                ('pending', models.BooleanField(default=False, help_text='True while human verification is required; pending links are excluded from every estimate component.')),
                ('note', models.CharField(blank=True, max_length=240)),
                ('counterpart_tree', models.ForeignKey(blank=True, help_text='The other tree row involved (conflict/renumber pairs).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.tree')),
                ('interval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identity_links', to='inventory.surveyinterval')),
                ('t1_measurement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.treemeasurement')),
                ('t2_measurement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.treemeasurement')),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interval_links', to='inventory.tree')),
            ],
            options={
                'ordering': ['interval', 'tree__plot__code', 'tree__current_field_number'],
                'unique_together': {('interval', 'tree')},
            },
        ),
    ]
